### ISSUE TITLE
mood_note character-limit isn't 255

### ISSUE THREAD

**Issue by blankster** [hellocodeco/old-exist-api-docs#2]
The current character limit (via website) is 250 characters. 

![image](https://user-images.githubusercontent.com/1443109/69922147-f7e8c380-1499-11ea-8764-b3ac79f8ae78.png)

Based on the current API documentation (http://developer.exist.io/#list-of-attributes), 255 characters should be the limit.

![image](https://user-images.githubusercontent.com/1443109/69922157-1a7adc80-149a-11ea-99ec-c6851fc08daf.png)

Besides the limit should be different for the API than the website, this seems to be wrong.

**Comment by joshsharp** [comment]
Thanks, it is indeed 250.
